# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bind = SUPER SHIFT, P, exec, helium-browser --incognito
# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
# Test comment
# bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"

unbind = SUPER SHIFT, B
unbind = SUPER SHIFT, F
unbind = SUPER, W
unbind = SUPER, X
unbind = SUPER, C
unbind = SUPER, V
bind = SUPER, X, killactive

bind = SUPER, A, workspace, 11
bind = SUPER, B, workspace, 12
bind = SUPER, C, workspace, 13
bind = SUPER, D, workspace, 14
bind = SUPER, E, workspace, 15
# bind = SUPER, F, workspace, 16
bind = SUPER, G, workspace, 17
bind = SUPER, H, workspace, 18
bind = SUPER, I, workspace, 19
# bind = SUPER, J, workspace, 20
# bind = SUPER, K, workspace, 21
bind = SUPER, L, workspace, 22
bind = SUPER, M, workspace, 23
bind = SUPER, N, workspace, 24
# bind = SUPER, O, workspace, 25
# bind = SUPER, P, workspace, 26
bind = SUPER, Q, workspace, 27
bind = SUPER, R, workspace, 28
# bind = SUPER, S, workspace, 29
# bind = SUPER, T, workspace, 30
bind = SUPER, U, workspace, 31
bind = SUPER, V, workspace, 32
bind = SUPER, W, workspace, 33
# bind = SUPER, X, workspace, 34
bind = SUPER, Y, workspace, 35
bind = SUPER, Z, workspace, 36

bindd = SUPER SHIFT, A, Move window to workspace 11, movetoworkspace, 11
bindd = SUPER SHIFT, B, Move window to workspace 12, movetoworkspace, 12
bindd = SUPER SHIFT, C, Move window to workspace 13, movetoworkspace, 13
bindd = SUPER SHIFT, D, Move window to workspace 14, movetoworkspace, 14
bindd = SUPER SHIFT, E, Move window to workspace 15, movetoworkspace, 15
# bindd = SUPER SHIFT, F, Move window to workspace 16, move,toworkspace, 16
bindd = SUPER SHIFT, G, Move window to workspace 17, movetoworkspace, 17
bindd = SUPER SHIFT, H, Move window to workspace 18, movetoworkspace, 18
bindd = SUPER SHIFT, I, Move window to workspace 19, movetoworkspace, 19
# bindd = SUPER SHIFT, A, Move window to workspace 20, movetoworkspace, 20
# bindd = SUPER SHIFT, A, Move window to workspace 21, movetoworkspace, 21
bindd = SUPER SHIFT, L, Move window to workspace 22, movetoworkspace, 22
bindd = SUPER SHIFT, M, Move window to workspace 23, movetoworkspace, 23
bindd = SUPER SHIFT, N, Move window to workspace 24, movetoworkspace, 24
# bindd = SUPER SHIFT, A, Move window to workspace 25, movetoworkspace, 25
# bindd = SUPER SHIFT, A, Move window to workspace 26, movetoworkspace, 26
bindd = SUPER SHIFT, Q, Move window to workspace 27, movetoworkspace, 27
bindd = SUPER SHIFT, R, Move window to workspace 28, movetoworkspace, 28
# bindd = SUPER SHIFT, A, Move window to workspace 29, movetoworkspace, 29
# bindd = SUPER SHIFT, A, Move window to workspace 30, movetoworkspace, 30
bindd = SUPER SHIFT, U, Move window to workspace 31, movetoworkspace, 31
bindd = SUPER SHIFT, V, Move window to workspace 32, movetoworkspace, 32
bindd = SUPER SHIFT, W, Move window to workspace 33, movetoworkspace, 33
# bindd = SUPER SHIFT, A, Move window to workspace 34, movetoworkspace, 34
bindd = SUPER SHIFT, Y, Move window to workspace 35, movetoworkspace, 35
bindd = SUPER SHIFT, Z, Move window to workspace 36, movetoworkspace, 36

# x s f t j k o p, Omarchy menu, exec, omarchy-menu
# x f t j s k o p
# bind = SUPER, C, workspace, 13 conflicts with copy
# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
